### PR TITLE
Finished User reviews, Chef Replies, and Bookings page models

### PR DESCRIPTION
**Pull request by trishastlouis**

### CODE REVIEW

**Review by leopolicastro — CHANGES_REQUESTED** [review]

**Review by cececlar — COMMENTED** [review]
Chef should be an ObjectID that references the User table, User should also reference the user table.

**Review by cececlar — COMMENTED** [review]
Chef should be an ObjectID that references the User table, User should also reference the user table. 

ReviewId in userReviewSchema -- is this referencing the id of the review? If so, that's generated for you by MongoDB so you don't need to explicitly set it.

**Review by cececlar — COMMENTED** [review]
Chef should be an ObjectID that references the User table, User should also reference the user table. 

ReviewId in userReviewSchema -- is this referencing the id of the review? If so, that's generated for you by MongoDB so you don't need to explicitly set it. 

Rating field in userReviewSchema should be represented as an array of objects by surrounding the value of the field in [ ].

**Review by cececlar — CHANGES_REQUESTED** [review]
Do you want the fields for each model to be capitalized? In some places they are capitalized and in others they aren't. I suggest lowercasing all fields for all models. Also rather than inputting `type: []`, you can wrap the description for fields that will have an embedded array in square brackets to denote that they will have more than one value. Date and time fields should also be changed to `type: Date`.

**Pull request merged**
